var objmeta = {
    "home": { 
        "title":"AWT ERP & LMS Software for Schools, Colleges & Universities - Abuzz Webtec",
        "keywords": "AWT education erp software, education erp systems, college-erp software, school management software, university management system, learning management software, campus management system, autonomous college management system software, higher education erp software", 
        "desc": "All-in-one ERP & LMS for schools, colleges (incl. autonomous) & universities. Manage academics, fees, staff & more. Request your free demo today!" 
    }
    , "schoolmanagementsystem": { 
        "title":"School Management System & AWT ERP Software - Abuzz Webtech",
        "keywords": "school management software, school management system, education management system, student management software, education erp software education erp, education erp systems, School erp", 
        "desc": "Smart school management system with ERP software to manage students, fees & exams. Easy-to-use, secure & perfect for schools. Contact us today!" 
    }
    , "collegemanagement": { 
        "title":"AWT College ERP Software & Management System - Abuzz Webtech",
        "keywords": "education erp software, college ERP software, college-cms college managemet software, erp college software, college-erp, college managemet system, college-erp-software, learning management system for colleges, best erp software for colleges", 
        "desc": "Comprehensive college ERP software to manage admissions, finance, faculty & academics. Secure, scalable & built for modern higher education. Contact us today!" 
    }
    , "autonomouscollege": { 
        "title":"AWT Autonomous College ERP & Management System - Abuzz Webtech", 
        "keywords": "autonomous college management system software, campus management system, university erp software, education erp software, campus erp software, autonomous erp software, erp autonomous college system software, autonomous erp software system", 
        "desc": "Streamline academics, exams, staff & administration with our autonomous ERP system. Designed for modern autonomous colleges – secure & scalable." 
    }
    , "universitiesmanagement": { 
        "title":"AWT University Management System & ERP Software - Abuzz Webtech",
        "keywords": "university management system, university erp software, erp system for university, erp university, educational erp software, erp software for educational institutes india, learning management system for university, education erp systems, best erp software for colleges",
        "desc": "Smart university management system with ERP to handle academics, admissions & finance. Secure & scalable. Book a demo today!" 
    }
    , "learningmanagement": { 
        "title":"AWT Learning Management System (LMS) & ERP Software - Abuzz Webtech", 
        "keywords": "learning management software, ERP Leaning Management System, Best Leaning Management System, LMS erp System Software, LMS ERP, LMS erp Software, education erp software, university erp system, leaning management system, online learning management system", 
        "desc": "Powerful learning management system (LMS) with ERP to manage courses, students & e-learning. Secure, scalable & user-friendly. Request a demo today!" 
    }
    , "hospitalmanagementsystem": { 
         "title":"AI-Enabled Hospital Management System | Abuzz Webtech",
         "keywords": "Hospital Management System, Hospital ERP, Healthcare Management Software, Patient Management System, Electronic Health Records (EHR), Medical Billing Software, Appointment Scheduling, Hospital Information System (HIS), Clinic Management, Doctor Portal, Pharmacy Management, Laboratory Management, Telemedicine Software, Healthcare Analytics, Cloud-Based Hospital Software, Hospital Administration", 
         "desc": "Optimize hospital operations with our advanced Hospital Management System. Streamline patient records, appointments, billing, pharmacy, lab management, and more with our secure and cloud-based healthcare management software for seamless hospital administration." 
    }
    , "practicemanagementsystem": {  "title":"AI-Enabled  Practice Management System | Abuzz Webtech","keywords": "Practice Management System, Medical Practice Software, Healthcare Management Software, Patient Scheduling, Electronic Health Records (EHR), Medical Billing Software, Clinic Management System, Appointment Scheduling, Telemedicine Platform, Physician Practice Management, Healthcare Workflow Automation, Practice Billing, Insurance Claims Management, Cloud-Based Medical Software, Healthcare Analytics", "desc": "Streamline your medical practice with our advanced Practice Management System. Manage patient records, appointments, billing, telemedicine, and insurance claims seamlessly with our secure and cloud-based healthcare management software for clinics and healthcare providers." }
    , "spasandsalons": { "title":"AI-Enabled  Spa and Salon | Abuzz Webtech", "keywords": "Spa Management Software, Salon Management System, Beauty Salon Software, Spa Booking System, Salon Scheduling Software, Appointment Management, Online Booking for Salons, Client Management, Spa POS System, Salon POS Software, Hair Salon Software, Wellness Center Management, Beauty Business Software, Cloud-Based Spa Software, Staff Scheduling, Customer Loyalty Program", "desc": "Enhance your spa and salon business with our Spa & Salon Management Software. Streamline appointments, client management, billing, and staff scheduling with our cloud-based salon booking system for a seamless and efficient beauty business experience." }
    , "insurancetpaservice": { "title":"PreInsurance Verification Process", "keywords": "Insurance TPA Services, Third-Party Administrator, TPA Health Insurance, Claims Processing, Insurance Claims Management, Healthcare TPA, Medical Billing Services, Cashless Insurance, Policy Administration, Health Insurance Processing, Insurance Workflow Automation, Insurance Settlement, Claims Adjudication, Employee Health Benefits, Insurance Support Services, Cloud-Based TPA Software", "desc": "Optimize your insurance claims process with our Insurance TPA Services. Streamline claims management, policy administration, cashless insurance processing, and medical billing with our efficient and secure third-party administrator solutions for insurers and healthcare providers." }
    , "humanresourcemanagement": { "title":"AI-Enabled  Human Resourse Management System | Abuzz Webtech", "keywords": "Human Resource Management System, HRMS Software, HR Management Software, Employee Management System, Payroll Software, Talent Management, Recruitment Software, Workforce Management, Performance Management, HR Automation, Employee Onboarding, Attendance Tracking, Leave Management, HR Analytics, Cloud-Based HR Software, HR ERP Solution", "desc": "Optimize your HR processes with our advanced Human Resource Management System (HRMS). Streamline employee management, payroll, recruitment, performance tracking, and HR automation with our cloud-based and user-friendly HR software for businesses of all sizes." }
    , "payrollmanagement": { "title":"AI-Enabled Payroll Management System | Abuzz Webtech", "keywords": "Payroll Management System, Payroll Software, Salary Processing, Employee Payroll System, HR and Payroll Software, Payroll Automation, Tax Compliance, Payroll Processing Software, Cloud-Based Payroll, Employee Salary Management, Payroll Tax Calculation, Payroll ERP, Direct Deposit Payroll, Payroll Reporting, Payroll Outsourcing, Wage Management", "desc": "Streamline your payroll process with our Payroll Management System. Automate salary calculations, tax compliance, direct deposits, and payroll reporting with our secure and cloud-based payroll software for businesses of all sizes." }
    , "bgc": {  "title":"Employee Background Verification CRM | AWT","keywords": "Employee Background Verification, Background Check Services, Pre-Employment Screening, Employee Screening, Criminal Record Check, Employment History Verification, Identity Verification, Corporate Background Check, Education Verification, Reference Check, Drug Testing Services, Workforce Screening, Compliance Screening, Candidate Verification, Background Screening Solutions, HR Verification Services", "desc": "Ensure a safe and trustworthy workplace with our Employee Background Verification Services. Conduct comprehensive pre-employment screening, criminal record checks, education verification, and identity verification with our reliable and efficient background screening solutions." }
    , "taskmanagement": { "title":"Employee Daily Task Management System | AWT", "keywords": "Task Management Software, Project Management, Team Collaboration Tools, Task Tracking, Productivity Software, Workflow Automation, To-Do List App, Task Scheduling, Work Management System, Agile Task Management, Task Planner, Online Task Manager, Task Assignment, Time Management Software, Cloud-Based Task Management, Kanban Board", "desc": "Boost productivity with our Task Management Software. Easily track tasks, manage projects, collaborate with teams, and streamline workflows with our user-friendly and cloud-based task tracking solution for businesses and individuals." }
    , "documentationprocess": { "title":"Documentation Scanning and Storing | AWT", "keywords": "Documentation Process, Document Management System, Workflow Documentation, Business Documentation, Process Documentation, Compliance Documentation, Digital Documentation, Document Workflow Automation, Standard Operating Procedures (SOP), Knowledge Management, Record Keeping Software, Policy Documentation, Cloud-Based Document Management, Document Approval Process, Electronic Documentation", "desc": "Streamline your documentation process with our efficient Document Management System. Automate workflow documentation, ensure compliance, and improve record-keeping with our secure and cloud-based documentation solutions for businesses and organizations." }
    , "inventoryandstock": {"title":"Inventory Management System | AWT",  "keywords": "Inventory Management System, Stock Management Software, Warehouse Management, Inventory Tracking, Inventory Control, Stock Monitoring, Supply Chain Management, Inventory Optimization, Barcode Inventory System, Product Stock Management, Cloud-Based Inventory Software, Retail Inventory Management, Inventory Automation, Inventory Reporting, ERP Inventory System", "desc": "Optimize your inventory and stock management with our Inventory Management System. Track stock levels, manage warehouses, automate reordering, and streamline supply chain operations with our cloud-based and user-friendly inventory control software." }
    , "library": { "title":"Library Management System | AWT", "keywords": "Library Management System, Digital Library Software, Library Catalog Management, Book Inventory System, Online Library System, Library Automation, Library Database, eLibrary Software, Library Lending System, Library OPAC, Cloud-Based Library Software, Library Resource Management, Academic Library System, Public Library Software, Library Circulation System", "desc": "Enhance library efficiency with our Library Management System. Automate book cataloging, lending, inventory tracking, and digital resource management with our cloud-based and user-friendly library software for schools, universities, and public libraries." }
    , "eventmanagement": { "keywords": "Event Management Software, Event Planning, Event Registration System, Conference Management, Online Event Booking, Event Scheduling, Virtual Event Platform, Event Ticketing, Corporate Event Management, Wedding Planning Software, Event Marketing, Trade Show Management, Festival Management, Cloud-Based Event Software, Event Coordination Tools", "desc": "Streamline your events with our Event Management Software. Automate event planning, registration, ticketing, and scheduling with our cloud-based and user-friendly event coordination platform for corporate, virtual, and social events." }
    , "matrimony": { "title":"Matrimony Portal and Website", "keywords": "Matrimony CRM, Matrimonial Website Software, Marriage Bureau Software, Matchmaking CRM, Matrimonial Portal, Online Matrimony Platform, Wedding Matchmaking Software, Relationship Management System, Bride and Groom Matching, Matrimony Website Development, Marriage Registration System, Matrimony Lead Management, Matrimonial Membership Management, Cloud-Based Matrimony CRM, Matchmaking Automation", "desc": "Enhance your matchmaking services with our Matrimony CRM and Website Solution. Manage profiles, automate matchmaking, handle memberships, and streamline communication with our cloud-based and user-friendly matrimonial website and CRM software." }
    , "ottplatform": { "title":"OTT Portal, Website & Mobile Apps", "keywords": "OTT Platform, Video Streaming Service, On-Demand Streaming, Live Streaming Platform, OTT App Development, Video Hosting Software, Subscription-Based Streaming, OTT Content Management, Video Monetization, IPTV Solution, Streaming Media Service, Cloud-Based OTT Solution, Multi-Device Streaming, Video Distribution Platform, VOD Platform", "desc": "Launch your own OTT platform with our cutting-edge video streaming solution. Deliver on-demand and live streaming content with high-quality playback, multi-device compatibility, and seamless monetization options for a premium viewing experience." }
    , "websitebuilder": {  "title":"Website Builder | AWT","keywords": "OTT Platform, Video Streaming Service, On-Demand Streaming, Live Streaming Platform, OTT App Development, Video Hosting Software, Subscription-Based Streaming, OTT Content Management, Video Monetization, IPTV Solution, Streaming Media Service, Cloud-Based OTT Solution, Multi-Device Streaming, Video Distribution Platform, VOD Platform", "desc": "Launch your own OTT platform with our cutting-edge video streaming solution. Deliver on-demand and live streaming content with high-quality playback, multi-device compatibility, and seamless monetization options for a premium viewing experience." }
    , "become a partner": { "title":"Become a partner with AWT", "keywords": "Become a Partner, Business Partnership, Partnership Program, Affiliate Program, Channel Partner, Reseller Program, Franchise Opportunity, Business Collaboration, Strategic Partnership, B2B Partnership, Corporate Alliance, Distribution Partner, White Label Partnership, Partner with Us, Joint Venture Opportunities", "desc": "Join our Partnership Program and grow your business with us. Explore exciting collaboration opportunities, reseller programs, and strategic alliances to expand your reach and maximize success. Become a partner today!" }
    , "blogs": { "title":"Blogs | AWT", "keywords": "awthub", "desc": "awthub" }
    , "contact us": {  "title":"Abuzz Webtech Private Limited","keywords": "awthub", "desc": "awthub" }
}